#spring.ai.gemini.api-key=AQ.Ab8RN6KNJOuGNu8ENoRTX6nto-Spsv2yss7p0XtY9DdDCycblQ
#spring.ai.gemini.chat.options.model=gemini-2.5-flash

spring.ai.openai.api-key=AQ.Ab8RN6I03wcuYFmNJAq2GQzE555IMPkt71rG6VXqqZ8xympCEA
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.chat.options.model=gemini-2.5-flash